CREATE TABLE IF NOT EXISTS entries (id TEXT PRIMARY KEY, name TEXT NOT NULL, message TEXT NOT NULL, date TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS post_limits (visitor TEXT PRIMARY KEY, last_post INTEGER NOT NULL);
